---
- name: create polkadot service file
  template:
    src: polkadot.service.j2
    dest: /etc/systemd/system/{{ chain_stub }}.service
    owner: root
    group: root
    mode: 0600

- name: enable nginx proxy
  include_tasks: nginx-proxy.yml

- name: enable source of truth sync
  include_tasks: configure-sync.yml
  when: use_source_of_truth

- name: prepare envoy personalization
  include_tasks: envoy-personalization.yml
  when: enable_envoy_personalization

- name: restart polkadot service
  shell: |
    set -o pipefail
    systemctl stop {{ chain_stub }}.service || true
    systemctl daemon-reload
    systemctl enable --now {{ chain_stub }}.service
  args:
    executable: /bin/bash
  changed_when: False